version: 0.2

phases:
  pre_build:
    commands:
      - echo docker info
      - docker info
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 538782569624.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build start on `date`
      - echo Building the docker image
      - docker build -t mintu-docker-repo .
      - docker tag mintu-docker-repo:latest 538782569624.dkr.ecr.us-east-1.amazonaws.com/mintu-docker-repo:latest
  post_build:
    commands:
      - echo Build complete on `date`
      - echo Pushing the docker image...
      - docker push 538782569624.dkr.ecr.us-east-1.amazonaws.com/mintu-docker-repo:latest